description: >
  Select the version of Ruby to use. Uses CircleCI's highly cached convenience
  images built for CI.
docker:
  - image: 'cimg/ruby:<<parameters.tag>>'
parameters:
  tag:
    default: '2.7'
    description: The `circleci/ruby` Docker image version tag.
    type: string
